version: '2'


services:
  server:
    container_name: graphql_server
    image: graphql_server
#    restart: always
#    build:
#      context: .
#      dockerfile: .docker/app.dockerfile
    ports:
      - '3005:3005'
      - '3000:3000'
    links:
      - db
  db:
    container_name: mongo_db
    image: mongo
    volumes:
      - C:\Users\Good\Desktop\Graphql\gateway\db:/data/db
    ports:
      - '27017:27017'
  admin-mongo:
    image: 0x59/admin-mongo:latest
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - CONN_NAME=mongo
      - DB_HOST=mongo
    links:
      - db
